Response saved to: statement_analysis_page12_20250211-121653.json
Successfully processed PDF page: Statement_163322_10212003_27_Jun_2024_page_12.jpg
Run status: in_progress
Run status: in_progress
Run status: failed
2025-02-11 12:16:54,230 - assistant_client - ERROR - Error while waiting for response: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-Q6L2qFtrrKA6toV9MhDKfC?se=2025-02-11T13%3A16%3A49Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=0vhB09t%2B8vMjPw77nuWJ2bNL2WBItog%2B7jX5y84f33M%3D.')
Traceback (most recent call last):
  File "/home/runner/workspace/assistant_client.py", line 197, in wait_for_response
    raise ResponseTimeoutError(error_msg)
exceptions.ResponseTimeoutError: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-Q6L2qFtrrKA6toV9MhDKfC?se=2025-02-11T13%3A16%3A49Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=0vhB09t%2B8vMjPw77nuWJ2bNL2WBItog%2B7jX5y84f33M%3D.')
Error processing Statement_163322_10212003_27_Jun_2024_page_6.jpg: Error while waiting for response: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-Q6L2qFtrrKA6toV9MhDKfC?se=2025-02-11T13%3A16%3A49Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=0vhB09t%2B8vMjPw77nuWJ2bNL2WBItog%2B7jX5y84f33M%3D.')
Run status: in_progress
Run status: in_progress
Run status: in_progress
Run status: in_progress
Run status: in_progress
Run status: failed
2025-02-11 12:16:54,796 - assistant_client - ERROR - Error while waiting for response: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-GSiZEqR8j3T5uPWRK5Vvqu?se=2025-02-11T13%3A16%3A50Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=GVLUVqKv1xVGC5tjeNC1WJVxvTvPre6mqD/87OT37ME%3D.')
Traceback (most recent call last):
  File "/home/runner/workspace/assistant_client.py", line 197, in wait_for_response
    raise ResponseTimeoutError(error_msg)
exceptions.ResponseTimeoutError: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-GSiZEqR8j3T5uPWRK5Vvqu?se=2025-02-11T13%3A16%3A50Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=GVLUVqKv1xVGC5tjeNC1WJVxvTvPre6mqD/87OT37ME%3D.')
Error processing Statement_163322_10212003_27_Jun_2024_page_3.jpg: Error while waiting for response: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-GSiZEqR8j3T5uPWRK5Vvqu?se=2025-02-11T13%3A16%3A50Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=GVLUVqKv1xVGC5tjeNC1WJVxvTvPre6mqD/87OT37ME%3D.')