Successfully processed PDF page: Statement_163322_10212003_27_Jun_2024_page_11.jpg
Run status: failed
2025-02-11 14:27:46,041 - assistant_client - ERROR - Error while waiting for response: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-BfeeHwQJdYuQrWPP3k17uq?se=2025-02-11T15%3A27%3A40Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=owVRBOeAVedAfx1bdn8aXsQPa%2BpjFDAJilDSxA6zpOQ%3D.')
Traceback (most recent call last):
  File "/home/runner/workspace/assistant_client.py", line 197, in wait_for_response
    raise ResponseTimeoutError(error_msg)
exceptions.ResponseTimeoutError: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-BfeeHwQJdYuQrWPP3k17uq?se=2025-02-11T15%3A27%3A40Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=owVRBOeAVedAfx1bdn8aXsQPa%2BpjFDAJilDSxA6zpOQ%3D.')
Error processing Statement_163322_10212003_27_Jun_2024_page_8.jpg: Error while waiting for response: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-BfeeHwQJdYuQrWPP3k17uq?se=2025-02-11T15%3A27%3A40Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=owVRBOeAVedAfx1bdn8aXsQPa%2BpjFDAJilDSxA6zpOQ%3D.')
Run status: failed
2025-02-11 14:27:46,246 - assistant_client - ERROR - Error while waiting for response: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-CfaKAoMmMc7NhALR4FuzGD?se=2025-02-11T15%3A27%3A41Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=IIuKcJJyS7Nep%2BrUjozHO52s2xcLIvKxiDis5B3TOXA%3D.')
Traceback (most recent call last):
  File "/home/runner/workspace/assistant_client.py", line 197, in wait_for_response
    raise ResponseTimeoutError(error_msg)
exceptions.ResponseTimeoutError: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-CfaKAoMmMc7NhALR4FuzGD?se=2025-02-11T15%3A27%3A41Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=IIuKcJJyS7Nep%2BrUjozHO52s2xcLIvKxiDis5B3TOXA%3D.')
Error processing Statement_163322_10212003_27_Jun_2024_page_1.jpg: Error while waiting for response: Run failed with status: failed, error: LastError(code='invalid_image_url', message='Timeout while downloading https://fileserviceuploadsperm.blob.core.windows.net/files/file-CfaKAoMmMc7NhALR4FuzGD?se=2025-02-11T15%3A27%3A41Z&sp=r&sv=2024-08-04&sr=b&rscc=max-age%3D3599%2C%20immutable%2C%20private&rscd=attachment%3B%20filename%3Dimage.jpg&sig=IIuKcJJyS7Nep%2BrUjozHO52s2xcLIvKxiDis5B3TOXA%3D.')